workspace:
  base: /drone
  path: src/github.com/fusionapp/clj-documint
pipeline:
  restore_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    restore: true
    mount:
      - m2
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event:
        - push
        - pull_request
        - tag
  lein:
    image: clojure:lein
    pull: true
    commands:
      - mkdir -p m2
      # Avoid `with-profile` because of bad behaviour in `lein-localrepo`:
      # https://github.com/kumarshantanu/lein-localrepo/issues/13
      - lein localrepo install --repo m2 resources/css2xslfo1_6_2.jar com.fusionapp/css2xslfo 1.6.2
      - lein with-profile +drone uberjar
      - lein with-profile +drone codox
    when:
      event:
        - push
        - pull_request
        - tag
  rebuild_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    rebuild: true
    mount:
      - m2
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: push
      branch:
        - master
  flush_cache:
    image: plugins/s3-cache
    pull: true
    endpoint: https://s3.amazonaws.com
    root: /drone-cache-fusionapp-useast
    flush: true
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: push
      branch:
        - master
  publish_docs:
    image: plugins/gh-pages
    pages_directory: target/codox
    upstream_name: git@github.com:fusionapp/clj-documint.git
    secrets:
      - git_push_ssh_key
    when:
      event: push
      branch: master
  publish:
    image: plugins/ecr
    region: eu-west-1
    registry: 801493518741.dkr.ecr.eu-west-1.amazonaws.com
    repo: 801493518741.dkr.ecr.eu-west-1.amazonaws.com/clj-documint
    tags:
      - ${DRONE_BRANCH}
      - git-${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: master
    secrets:
      - ecr_access_key
      - ecr_secret_key
  deploy-uat:
    image: peloton/drone-rancher
    url: https://rancher.fusionapp.com
    service: Fusion/clj-documint
    docker_image: 801493518741.dkr.ecr.eu-west-1.amazonaws.com/clj-documint:git-${DRONE_COMMIT_SHA}
    start_first: false
    confirm: true
    timeout: 480
    when:
      event: push
      branch: master
    secrets:
      - source: rancher_nonprod_access_key
        target: rancher_access_key
      - source: rancher_nonprod_secret_key
        target: rancher_secret_key
  deploy-production:
    image: peloton/drone-rancher
    url: https://rancher.fusionapp.com
    service: fusion/clj-documint
    docker_image: 801493518741.dkr.ecr.eu-west-1.amazonaws.com/clj-documint:git-${DRONE_COMMIT_SHA}
    start_first: false
    confirm: true
    timeout: 480
    when:
      event: deployment
      environment: production
    secrets:
      - source: rancher_prod_access_key
        target: rancher_access_key
      - source: rancher_prod_secret_key
        target: rancher_secret_key
  slack:
    image: plugins/slack
    secrets:
      - slack_webhook
    when:
      status:
        - success
        - failure
  slack_production:
    image: plugins/slack
    secrets:
      - slack_webhook
    channel: production
    when:
      event: deployment
      environment: production
      status:
        - success
        - failure
branches:
  - master
  - staging
  - trying
