workspace:
  base: /drone
  path: src/github.com/fusionapp/clj-documint
pipeline:
  restore_cache:
    image: appleboy/drone-sftp-cache
    server: sftp-cache.drone7.non-production.fusionapp.com
    port: 45945
    username: drone-cache
    path: /drone-cache
    restore: true
    ignore_branch: true
    mount:
      - m2
    when:
      event:
        - push
        - pull_request
        - tag
    secrets:
      - sftp_cache_password
  lein:
    image: idnar/lein
    pull: true
    commands:
      # Avoid `with-profile` because of bad behaviour in `lein-localrepo`:
      # https://github.com/kumarshantanu/lein-localrepo/issues/13
      - /usr/local/bin/lein localrepo install --repo m2 resources/css2xslfo1_6_2.jar com.fusionapp/css2xslfo 1.6.2
      - /usr/local/bin/lein with-profile +drone uberjar
      - /usr/local/bin/lein with-profile +drone codox
    when:
      event:
        - push
        - pull_request
        - tag
  rebuild_cache:
    image: appleboy/drone-sftp-cache
    server: sftp-cache.drone7.non-production.fusionapp.com
    port: 45945
    username: drone-cache
    path: /drone-cache
    rebuild: true
    ignore_branch: true
    mount:
      - m2
    when:
      event: push
      branch: master
    secrets:
      - sftp_cache_password
  publish_docs:
    image: plugins/gh-pages
    pages_directory: target/codox
    upstream_name: git@github.com:fusionapp/clj-documint.git
    secrets:
      - git_push_ssh_key
    when:
      event: push
      branch: master
  publish:
    image: plugins/docker
    repo: eu.gcr.io/fusion-168903/clj-documint
    tags:
      - ${DRONE_BRANCH}
      - git-${DRONE_COMMIT_SHA}
    registry: eu.gcr.io
    mirror: https://eu-mirror.gcr.io
    username: _json_key
    when:
      event: push
      branch: master
    secrets:
      - docker_password
  deploy-uat:
    image: peloton/drone-rancher
    url: https://rancher.fusionapp.com
    service: Fusion/clj-documint
    docker_image: eu.gcr.io/fusion-168903/clj-documint:git-${DRONE_COMMIT_SHA}
    start_first: false
    confirm: true
    timeout: 120
    when:
      event: push
      branch: master
    secrets:
      - source: rancher_nonprod_access_key
        target: rancher_access_key
      - source: rancher_nonprod_secret_key
        target: rancher_secret_key
  deploy-production:
    image: peloton/drone-rancher
    url: https://rancher.fusionapp.com
    service: fusion/clj-documint
    docker_image: eu.gcr.io/fusion-168903/clj-documint:git-${DRONE_COMMIT_SHA}
    start_first: false
    confirm: true
    timeout: 120
    when:
      event: deployment
      environment: production
    secrets:
      - source: rancher_prod_access_key
        target: rancher_access_key
      - source: rancher_prod_secret_key
        target: rancher_secret_key
  slack:
    image: plugins/slack
    secrets:
      - slack_webhook
    when:
      status:
        - success
        - failure
  slack_production:
    image: plugins/slack
    secrets:
      - slack_webhook
    channel: production
    when:
      event: deployment
      environment: production
      status:
        - success
        - failure
branches:
  - master
  - staging
  - trying
